In [47]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split



encoder = OneHotEncoder(handle_unknown='ignore', min_frequency=5)

df = pd.read_csv('Final_Augmented_Training_Data.csv')

max_len =(max([len(i) for i in df["Body"]]))
df.head()
#Had to do manuel encoding because the onehotencoder was did not have frequency encoding
discovered_words = set()
padded  = []
for text in df['Body']:
    words = text.split()
    for word in words:
        discovered_words.add(word)  

df['Tokens'] = df['Body'].str.split()

new_df = pd.DataFrame()
for word in discovered_words:
    new_df[word] = df['Tokens'].apply(lambda x: x.count(word))

X_Encoded = new_df.to_numpy()
print(X_Encoded)


/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[word] = df['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[word] = df['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[word] = df['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[word] = df['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/1367984163.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1)

In [48]:
Bayes_classifier = MultinomialNB()
X_train, X_test, y_train, y_test = train_test_split(X_Encoded, df['Jobs'], test_size=0.2, random_state=42)

Bayes_classifier.fit(X_train, y_train)
print(Bayes_classifier.score(X_test, y_test))




0.9875


In [49]:
from sklearn.metrics import f1_score
y_pred = Bayes_classifier.predict(X_test)
print(f1_score(y_test, y_pred, average='weighted'))


0.9874980465697766


In [50]:
#Now time to filter your mail data
df3 = pd.read_csv('output.csv')
df3['Body']= df3['Body'].apply(lambda x: str(x).replace('\n',' '))  

df3[~df3['Body'].str.lower().str.contains('<')] 


df3['Tokens'] = df3['Body'].str.split()
new_df2 = pd.DataFrame()
for word in discovered_words:
    new_df2[word] = df3['Tokens'].apply(lambda x: x.count(word))
X_Encoded2 = new_df2.to_numpy()

/tmp/ipykernel_65892/3378789559.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df2[word] = df3['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/3378789559.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df2[word] = df3['Tokens'].apply(lambda x: x.count(word))
/tmp/ipykernel_65892/3378789559.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axi

In [51]:
print(X_Encoded2.shape)
print(X_Encoded.shape)

(17006, 2497)
(800, 2497)


In [52]:


y_pred = Bayes_classifier.predict(X_Encoded2)
print(y_pred)
df3['Jobs'] = y_pred
df3 = df3[df3['Jobs']==1]
df3 = df3[~df3['From'].str.contains(r'github|bu|bu\.edu|boston university|github\.com|GradeScope|gradescope|gradescope\.com|invitations@linked.com', na=False, case=False)]
df3.to_csv('Filtered_Mail.csv', index=False)


[0 1 0 ... 0 0 0]


In [53]:
test = pd.read_csv('Filtered_Mail.csv')
print(test.shape)
test2 = pd.read_csv('output.csv')   
print(test2.shape)

(756, 7)
(17006, 5)


In [54]:
test.head(20)

Subject  \
0   Daniyal, your application was sent to Career M...   
1   Software Engineer III Python at JPMorganChase ...   
2   Daniyal, your application was sent to CyberCoders   
3                               27 people noticed you   
4   Daniyal, your application was sent to BeaconFi...   
5    Daniyal, your application was sent to Pronix Inc   
6   Daniyal, your application was sent to Elementa...   
7   Daniyal, your application was sent to Red Ceda...   
8   Daniyal, your application was sent to Richard,...   
9   Your application for NASA announcement ARC-25-...   
10  Daniyal, your application was sent to Paladin ...   
11                       Your application at ZoomInfo   
12  =?UTF-8?Q?Daniyal,_don=E2=80=99t_forget_to_com...   
13  Daniyal, your application was sent to Searchab...   
14        2Sigma School is hiring a Software Engineer   
15  Daniyal, your application was sent to Search S...   
16  Daniyal, start a conversation with your new co...   
17  =?UTF-8?Q?=E2=80=9Cintern=E2=80=9D:_Refonte_Le...   
18                            I still want to connect   
19  Daniyal, your application was sent to Addison ...   

                                                 From  \
0                LinkedIn <jobs-noreply@linkedin.com>   
1              Glassdoor Jobs <noreply@glassdoor.com>   
2                LinkedIn <jobs-noreply@linkedin.com>   
3            LinkedIn <messages-noreply@linkedin.com>   
4                LinkedIn <jobs-noreply@linkedin.com>   
5                LinkedIn <jobs-noreply@linkedin.com>   
6                LinkedIn <jobs-noreply@linkedin.com>   
7                LinkedIn <jobs-noreply@linkedin.com>   
8                LinkedIn <jobs-noreply@linkedin.com>   
9   USA Staffing Office <usastaffingoffice@usastaf...   
10               LinkedIn <jobs-noreply@linkedin.com>   
11                              no-reply@zoominfo.com   
12               LinkedIn <jobs-noreply@linkedin.com>   
13               LinkedIn <jobs-noreply@linkedin.com>   
14              LinkedIn <jobs-listings@linkedin.com>   
15               LinkedIn <jobs-noreply@linkedin.com>   
16  Aaminah Rahat via LinkedIn <invitations@linked...   
17  LinkedIn Job Alerts <jobalerts-noreply@linkedi...   
18  "Michael (via LinkedIn)" <messages-noreply@lin...   
19               LinkedIn <jobs-noreply@linkedin.com>   

                                 To                                   Date  \
0   Daniyal Ahmed <daniyala@bu.edu>  Sun, 22 Dec 2024 22:31:37 +0000 (UTC)   
1                   daniyala@bu.edu  Sat, 21 Dec 2024 01:35:16 +0000 (UTC)   
2   Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 20:08:52 +0000 (UTC)   
3   Daniyal Ahmed <daniyala@bu.edu>   Wed, 4 Dec 2024 01:12:21 +0000 (UTC)   
4   Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 21:22:55 +0000 (UTC)   
5   Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 20:11:57 +0000 (UTC)   
6   Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 20:16:17 +0000 (UTC)   
7   Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 21:43:09 +0000 (UTC)   
8   Daniyal Ahmed <daniyala@bu.edu>  Sun, 22 Dec 2024 20:44:00 +0000 (UTC)   
9        daniyala <daniyala@bu.edu>        Mon, 25 Nov 2024 21:35:34 +0000   
10  Daniyal Ahmed <daniyala@bu.edu>  Sun, 22 Dec 2024 22:27:17 +0000 (UTC)   
11                  daniyala@bu.edu        Fri, 06 Dec 2024 16:23:59 +0000   
12  Daniyal Ahmed <daniyala@bu.edu>  Tue, 26 Nov 2024 18:11:07 +0000 (UTC)   
13  Daniyal Ahmed <daniyala@bu.edu>  Mon, 25 Nov 2024 21:38:46 +0000 (UTC)   
14  Daniyal Ahmed <daniyala@bu.edu>  Mon, 18 Nov 2024 19:12:24 +0000 (UTC)   
15  Daniyal Ahmed <daniyala@bu.edu>  Sun, 22 Dec 2024 22:28:22 +0000 (UTC)   
16  Daniyal Ahmed <daniyala@bu.edu>   Thu, 5 Dec 2024 21:12:35 +0000 (UTC)   
17  Daniyal Ahmed <daniyala@bu.edu>   Sun, 8 Dec 2024 23:12:10 +0000 (UTC)   
18  Daniyal Ahmed <daniyala@bu.edu>  Tue, 12 Nov 2024 12:12:09 +0000 (UTC)   
19  Daniyal Ahmed <daniyala@bu.edu>  Thu, 21 Nov 2024 22:33:54 +0000 (UTC)   

           